owner: Banabyte
repo: status.banabyte.com

sites:
  # Banabyte Network Pages
  - name: Banabyte Website
    url: https://Banabyte.com
    expectedStatusCodes:
      - 200
      - 401
  - name: Banabyte CDN
    url: https://cdn.banabyte.com
    expectedStatusCodes:
      - 200
      - 401
  - name: Banabyte Panel
    url: https://panel.banabyte.com
    expectedStatusCodes:
      - 200
      - 401
  - name: Banabyte Radio
    url: https://live.banabyte.com
    expectedStatusCodes:
      - 200
      - 401
  - name: Status Page
    url: https://status.banabyte.com
    expectedStatusCodes:
      - 200
      - 401      


  # Banabyte Network Servers
  - name: Server 1
    url: https://co-us01.banabyte.com:2021
    expectedStatusCodes:
      - 200
      - 401
  - name: Server 2
    url: https://co-us02.banabyte.com:2031
    expectedStatusCodes:
      - 200
      - 401
  - name: Server 3
    url: https://co-us03.banabyte.com:2041
    expectedStatusCodes:
      - 200
      - 401

  # Banablock Network
  - name: BanaBlock.net
    url: https://banablock.net
    expectedStatusCodes:
      - 200
      - 401      

  # Active DNS Servers
  - name: DNS SERVER 1
    url: https://1.1.1.1
    expectedStatusCodes:
      - 200
      - 401
  - name: DNS SERVER 2
    url: https://dns.google
    expectedStatusCodes:
      - 200
      - 401

status-website:
  cname: status.banabyte.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Banabyte Backend Status Page
  introTitle: "Something isn't working?"
  introMessage: Join the [Discord](https://discord.banabyte.com) to report it!
  theme: dark

commitMessages:
  commitAuthorName: "ZEROPOINTBRUH"
  commitAuthorEmail: "wegj1@hotmail.com"

assignees:
  - ZEROPOINTBRUH
  - DamienVesper
